version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    working_dir: /app
    ports:
      - "8000:8000" # Exposes FastAPI on port 8000
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./doc_to_pdf
      dockerfile: Dockerfile
    container_name: frontend_service
    working_dir: /src
    ports:
      - "3000:3000" # Exposes React app on port 3000
    volumes:
      - ./doc_to_pdf:/src
    command: ["npm", "run", "start"]
